version: '3.8'

services:
  backend:
    build:
      context: ./backend  
    image: rajaramachandran/eventdesk:backend__main_v1 
  frontend:
    build:
      context: ./frontend 
    image: rajaramachandran/eventdesk:frontend__main_v1 