version: '3.8'

services:
  backend:
    build:
      context: ./backend  
    image: rajaramachandran/eventdesk:backend_dev_v1 
  frontend:
    build:
      context: ./frontend 
    image: rajaramachandran/eventdesk:frontend_dev_v1 