version: '3.8'

services:
  backend:
    image: rajaramachandran/eventdesk:backend_uat_v1
    environment:
      - JWT_SECRET=$JWT_SECRET
      - JWT_EXPIRES_IN=$JWT_EXPIRES_IN
      - PORT=$PORT
      - NODE_ENV=$NODE_ENV
      - DATABASE_URL=$DATABASE_URL
    networks:
      - dokploy-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=Host(`uatb.eventdesk.io`)"
        - "traefik.http.routers.backend.entrypoints=websecure"
        - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
        - "traefik.http.services.backend.loadbalancer.server.port=5002"
    ports:
      - "5002:5002"  

networks:
  eventdesk-network:
    driver: bridge
  dokploy-network:
    external: true
    
